# Generated by Django 4.2.8 on 2023-12-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rakendus", "0002_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="attempt_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="quiz",
            name="quiz_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
