# Generated by Django 4.2.8 on 2023-12-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rakendus", "0005_document_author_quiz_author"),
    ]

    operations = [
        migrations.RemoveField(model_name="document", name="author",),
        migrations.RemoveField(model_name="quiz", name="author",),
    ]
