# Generated by Django 4.2.8 on 2023-12-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rakendus", "0006_remove_document_author_remove_quiz_author"),
    ]

    operations = [
        migrations.DeleteModel(name="Document",),
        migrations.DeleteModel(name="Quiz",),
    ]
